- name: "Blocos Registro.BR"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: "Ler a lista em CSV"
      community.general.read_csv:
        path: RegistroBR.csv
        fieldnames: bloco,descricao,status
      register: lista
      delegate_to: localhost

    # - ansible.builtin.debug:
    #     msg: 'Bloco: {{item.bloco}} Desc:{{item.descricao}} Status:{{item.status}}'
    #   loop: "{{lista.list}}"

    - name: Criar o bloco teste
      netbox_prefix:
        netbox_url: http://infra.supop.serpro
        netbox_token: 0e06ec88dffeaa381cdaefcc081e76a149e1b217
        data:
          prefix: "{{item.bloco}}"
          description: "{{item.descricao}}"
          status: "{{item.status}}"
          tags: GSISE,INFOVIA
        state: present
      loop: "{{lista.list}}"