scrape_configs:
  - job_name: 'Monitoraa'
    metrics_path: /metrics
    scrape_interval: 15s
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0